### ISSUE TITLE
Could you add a readme?

### ISSUE THREAD

**Issue by garrrettt** [cedvdb/cisum#1]
Hey, I saw this project on reddit.com/r/piano, and I figured I'd take a look at the code. It would be a lot easier though if I could tell right off the bat which libraries and stuff you're using for the music notation and stuff. 

The file names aren't very helpful either, so I assume you used some sort of bundler that auto-generated random names for the files. So if you could just make a readme.md that generally explains what you're using to make it all happen, that would be awesome. 

As a fellow pianist, I'd like to mess around with the code, but I just need to know how it works without me having to finely comb through each line of code. Thanks.

**Comment by cedvdb** [comment]
Sorry I just saw this. This is just the compiled version. 5 years later I'm guessing you don't need this anymore so I'm closing
